# Generated by Django 5.1 on 2024-08-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images')),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
